name: DevTCBN1144
main: me.tcbndevelopment.DevTCBN
version: 0.0.1_a5
description: TheCatBoxNetwork Dev's Plugin
commands:
   test:
      description: Checks For Errors
      usage: /<command>
   inp:
      description: INPROGRESS
      usage: /<command>
   opme:
      description: INPROGRESS
      usage: /<command>
   adminmode:
      description: Admin Mode On/Off
      usage: /<command> <args>
   modmode:
      description: Mod Mode On/Off
      usage: /<command> on/off
   resetdeaths:
      description: Resets Deaths For Players
      usage: /<command>
   adminmode:
      description: Toggles Admin Mode
      usage: /<command> <args>
   staffcheck:
      description: Checks All Information
      usage: /<command>
   chelp:
      description: DevTCBN Help
      usage: /<command>
   cfeed:
      description: Feeds You
      usage: /<command>
   cfly:
      description: Lets You Fly
      usage: /<command> <args>
   pos:
      description: Gives Location
      usage: /<command>
   tellpos:
      description: Gives Location To Others
      usage: /<command>
   cheal:
      description: Heals you
      usage: /<command>
   gmc:
      description: Changes Your Gamemode To Creative
      usage: /<command>
   gma:
      description: Changes Your Gamemode To Adventure
      usage: /<command>
   gms:
      description: Changes Your Gamemode To Survival
      usage: /<command>
   gmsp:
      description: Changes Your Gamemode To Spectator
      usage: /<command>
